[project]
name = "kiri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.25",
    "django>=6.0.1",
    "django-allauth>=65.13.1",
    "django-htmx>=1.27.0",
    "django-pwa>=2.0.1",
    "django-storages>=1.14.6",
    "django-turnstile>=0.1.2",
    "gunicorn>=23.0.0",
    "huey>=2.6.0",
    "paramiko>=4.0.0",
    "pillow>=12.1.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "whitenoise>=6.11.0",
]
