name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_SSH_KEY }}
        port: 22
        script: |
          # 1. Add path to 'uv'
          export PATH=$PATH:$HOME/.local/bin

          # 2. Go to project folder
          cd /home/nwokikeonyeka/kiri

          # 3. Pull latest code
          git pull origin main

          # 4. Sync Dependencies
          uv sync

          # 5. Run Migrations
          uv run python manage.py migrate

          # 6. Collect Static
          uv run python manage.py collectstatic --noinput

          # 7. Restart Services (Kiri + Huey)
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart kiri
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart kiri-huey
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx

          echo "Deployment Complete! ðŸš€"
